In [16]:
# all the imports required for the project 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
# read in the teams data from the csv file
teams = pd.read_csv('teams_data.csv')

teams = teams.drop(columns = ["logo"])
teams.head()

   team_id   country                      team
0    50138     Italy  FC Internazionale Milano
1    50124     Spain        Atlético de Madrid
2    50111   Austria             SK Sturm Graz
3    52816     Italy               Atalanta BC
4    50050  Scotland                 Celtic FC

In [18]:
# read in the players_data from the csv file 
players = pd.read_csv("DAY_4/players_data.csv")

# we drop the weight, player image and height columns as we will not be using these in our analysis and they contain plenty of missing values
# we drop the position column as this has many blank values and field position provides us the data we need for looking at countries that specialise in certain areas of the field
players = players.drop(columns = ["position", "player_image", "weight(kg)", "height(cm)"])

players.head()

# rename team_id cloumn to match teams df for merging 
players = players.rename(columns = {"id_team" : "team_id"})

In [19]:
# read in the key stats from the csv file 

key_stats = pd.read_csv("DAY_4/key_stats_data.csv")

key_stats.head()

,id_player,distance_covered(km/h),top_speed,minutes_played,matches_appareance
0,250016833,43.71,30.35,360.0,4.0
1,250105927,41.94,34.55,360.0,4.0
2,250121533,38.39,35.47,360.0,4.0
3,250121294,46.61,32.26,360.0,4.0
4,250160436,44.67,33.39,360.0,4.0

In [20]:
# read in all remaing csv files
attacking_stats = pd.read_csv("DAY_4/attacking_data.csv")
goals_stats = pd.read_csv("DAY_4/goals_data.csv")
goalkeeping_stats = pd.read_csv("DAY_4/goalkeeping_data.csv")
defending_stats = pd.read_csv("DAY_4/defending_data.csv")
distribution_stats = pd.read_csv("DAY_4/distribution_data.csv")
discipline_stats = pd.read_csv("DAY_4/disciplinary_data.csv")
attempts_stats = pd.read_csv("DAY_4/attempts_data.csv")

In [21]:
# gather some more info on the data frames we now have
players.info()

teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_player       908 non-null    int64
 1   player_name     908 non-null    object
 2   nationality     908 non-null    object
 3   field_position  908 non-null    object
 4   age             908 non-null    int64
 5   team_id         908 non-null    int64
dtypes: int64(3), object(3)
memory usage: 42.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   team_id  36 non-null     int64
 1   country  36 non-null     object
 2   team     36 non-null     object
dtypes: int64(1), object(2)
memory usage: 996.0+ bytes

In [22]:
# get info about key stats
key_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_player               908 non-null    int64
 1   distance_covered(km/h)  727 non-null    float64
 2   top_speed               727 non-null    float64
 3   minutes_played          727 non-null    float64
 4   matches_appareance      727 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 35.6 KB

In [23]:
# get unique values for field position column 
# this gives us the option to group players by position for analysis
players.field_position.unique()

array(['Forward', 'Midfielder', 'Defender', 'Goalkeeper'], dtype=object)

In [24]:
# any statistics relating to player performance that are null have this replace with 0 
key_stats = key_stats.fillna(0)
attacking_stats = attacking_stats.fillna(0)
goals_stats = goals_stats.fillna(0)
goalkeeping_stats = goalkeeping_stats.fillna(0)
defending_stats = defending_stats.fillna(0)
distribution_stats = distribution_stats.fillna(0)
discipline_stats = discipline_stats.fillna(0)
attempts_stats = attempts_stats.fillna(0)

In [25]:
# we want to export our data frames to sql so we can run queries on them from there 
import sqlite3

# Connect to database
conn = sqlite3.connect("ucl_analysis.db")

# Export player and teams tables
players.to_sql("players", conn, if_exists="replace", index=False)
teams.to_sql("teams", conn, if_exists="replace", index=False)

# Export all tables containung stats
key_stats.to_sql("key_stats", conn, if_exists="replace", index=False)
attacking_stats.to_sql("attacking_stats", conn, if_exists="replace", index=False)
defending_stats.to_sql("defending_stats", conn, if_exists="replace", index=False)
distribution_stats.to_sql("distribution_stats", conn, if_exists="replace", index=False)
goalkeeping_stats.to_sql("goalkeeping_stats", conn, if_exists="replace", index=False)
discipline_stats.to_sql("discipline_stats", conn, if_exists="replace", index=False)
goals_stats.to_sql("goals_stats", conn, if_exists ="replace", index = False)
attempts_stats.to_sql("attempts_stats", conn, if_exists="replace", index = False)

# close connection with database
conn.close()