In [1]:
# all the imports required for the project 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# read in the teams data from the csv file
teams = pd.read_csv('teams_data.csv')

teams
teams.head()

,team_id,country,team,logo
0,50138,Italy,FC Internazionale Milano,https://img.uefa.com/imgml/TP/teams/logos/70x7...
1,50124,Spain,Atlético de Madrid,https://img.uefa.com/imgml/TP/teams/logos/70x7...
2,50111,Austria,SK Sturm Graz,https://img.uefa.com/imgml/TP/teams/logos/70x7...
3,52816,Italy,Atalanta BC,https://img.uefa.com/imgml/TP/teams/logos/70x7...
4,50050,Scotland,Celtic FC,https://img.uefa.com/imgml/TP/teams/logos/70x7...

In [7]:
# read in the players_data from the csv file 
players = pd.read_csv("DAY_4/players_data.csv")

players.head()

,id_player,player_name,nationality,field_position,position,weight(kg),height(cm),age,id_team,player_image
0,250016833,Harry Kane,England,Forward,STRIKER,65.0,188.0,31,50037,https://img.uefa.com/imgml/TP/players/1/2025/3...
1,250105927,Viktor Gyökeres,Sweden,Forward,NaN,NaN,NaN,26,50149,https://img.uefa.com/imgml/TP/players/1/2025/3...
2,250121533,Vinícius Júnior,Brazil,Forward,UNKNOWN,NaN,NaN,24,50051,https://img.uefa.com/imgml/TP/players/1/2025/3...
3,250121294,Tijjani Reijnders,Netherlands,Midfielder,CENTRAL_MIDFIELDER,NaN,NaN,26,50058,https://img.uefa.com/imgml/TP/players/1/2025/3...
4,250160436,Maghnes Akliouche,France,Midfielder,UNKNOWN,NaN,NaN,22,50023,https://img.uefa.com/imgml/TP/players/1/2025/3...